"""
FTP Service (vsftpd)
"""

import os
import re
from typing import Dict, Any, Optional
import logging

from .base import BaseService, ServiceResult, ServiceStatus


logger = logging.getLogger(__name__)


class FTPService(BaseService):
    """
    FTP Service implementation using vsftpd.
    Supports FTPS (FTP over TLS/SSL) for secure file transfers.
    """
    
    @property
    def name(self) -> str:
        return "ftp"
    
    @property
    def display_name(self) -> str:
        return "FTP Server (vsftpd)"
    
    @property
    def package_name(self) -> str:
        return "vsftpd"
    
    @property
    def service_name(self) -> str:
        return "vsftpd"
    
    @property
    def config_path(self) -> str:
        return "/etc/vsftpd.conf"
    
    @property
    def port(self) -> int:
        return 21
    
    @property
    def default_settings(self) -> Dict[str, Any]:
        return {
            "anonymous_enable": False,
            "local_enable": True,
            "write_enable": True,
            "local_umask": "022",
            "dirmessage_enable": True,
            "xferlog_enable": True,
            "connect_from_port_20": True,
            "xferlog_std_format": True,
            "listen": False,  # Use IPv6
            "listen_ipv6": True,
            "pam_service_name": "vsftpd",
            "userlist_enable": True,
            "tcp_wrappers": True,
            # Security settings
            "chroot_local_user": True,
            "chroot_list_enable": False,
            "allow_writeable_chroot": True,
            # TLS/SSL settings (FTPS)
            "ssl_enable": True,
            "force_local_data_ssl": True,
            "force_local_logins_ssl": True,
            "ssl_tlsv1": True,
            "ssl_sslv2": False,
            "ssl_sslv3": False,
            "rsa_cert_file": "/etc/ssl/certs/vsftpd.crt",
            "rsa_private_key_file": "/etc/ssl/private/vsftpd.key",
            # Passive mode
            "pasv_enable": True,
            "pasv_min_port": 40000,
            "pasv_max_port": 40100,
            "pasv_address": None,  # Will be set to server IP
            # Logging
            "log_ftp_protocol": True,
            "vsftpd_log_file": "/var/log/vsftpd.log",
            # Performance
            "idle_session_timeout": 600,
            "data_connection_timeout": 120,
            "max_clients": 100,
            "max_per_ip": 10,
        }
    
    def configure(self, settings: Dict[str, Any]) -> ServiceResult:
        """Configure vsftpd service"""
        try:
            # Merge with default settings
            config_settings = {**self.default_settings, **settings}
            
            # Build configuration content
            config_lines = ["# vsftpd configuration - generated by File Server Manager"]
            config_lines.append(f"# Generated at: {self._get_timestamp()}")
            config_lines.append("")
            
            # Main settings
            for key, value in config_settings.items():
                if value is None:
                    continue
                    
                if isinstance(value, bool):
                    config_lines.append(f"{key}={'YES' if value else 'NO'}")
                elif isinstance(value, str):
                    config_lines.append(f"{key}={value}")
                elif isinstance(value, int):
                    config_lines.append(f"{key}={value}")
            
            # Write configuration
            config_content = "\n".join(config_lines)
            self._write_config(config_content)
            
            # Setup TLS certificates if enabled
            if config_settings.get("ssl_enable", True):
                self._setup_tls_certs(config_settings)
            
            # Create necessary directories
            self._create_directories(config_settings)
            
            # Ensure ftp user exists
            self._ensure_ftp_user()
            
            # Restart service if running
            if self.get_status() == ServiceStatus.RUNNING:
                self.restart()
            
            return ServiceResult(
                success=True,
                message="FTP service configured successfully",
                data={"config_path": self.config_path}
            )
            
        except Exception as e:
            logger.error(f"Failed to configure FTP: {e}")
            return ServiceResult(
                success=False,
                message="Failed to configure FTP service",
                error=str(e)
            )
    
    def _get_timestamp(self) -> str:
        from datetime import datetime
        return datetime.utcnow().isoformat()
    
    def _setup_tls_certs(self, settings: Dict[str, Any]) -> None:
        """Setup TLS certificates for FTPS"""
        cert_file = settings.get("rsa_cert_file", "/etc/ssl/certs/vsftpd.crt")
        key_file = settings.get("rsa_private_key_file", "/etc/ssl/private/vsftpd.key")
        
        # Check if certificates already exist
        if os.path.exists(cert_file) and os.path.exists(key_file):
            return
        
        # Generate self-signed certificate
        cert_dir = os.path.dirname(cert_file)
        key_dir = os.path.dirname(key_file)
        
        os.makedirs(cert_dir, exist_ok=True)
        os.makedirs(key_dir, exist_ok=True)
        
        # Generate certificate using openssl
        try:
            self._run_command([
                "openssl", "req", "-x509", "-nodes",
                "-days", "365",
                "-newkey", "rsa:2048",
                "-keyout", key_file,
                "-out", cert_file,
                "-subj", "/C=US/ST=State/L=City/O=Organization/CN=fileserver"
            ])
            
            # Set permissions
            os.chmod(key_file, 0o600)
            os.chmod(cert_file, 0o644)
            
            logger.info("Generated FTPS certificates")
            
        except Exception as e:
            logger.warning(f"Could not generate TLS certificates: {e}")
    
    def _create_directories(self, settings: Dict[str, Any]) -> None:
        """Create necessary directories"""
        # Log directory
        log_file = settings.get("vsftpd_log_file", "/var/log/vsftpd.log")
        log_dir = os.path.dirname(log_file)
        if log_dir:
            os.makedirs(log_dir, exist_ok=True)
        
        # FTP home directory
        ftp_home = "/var/ftp"
        if not os.path.exists(ftp_home):
            os.makedirs(ftp_home)
            os.chmod(ftp_home, 0o755)
    
    def _ensure_ftp_user(self) -> None:
        """Ensure ftp user exists for anonymous access if needed"""
        try:
            # Check if ftp user exists
            result = self._run_command(["id", "ftp"], check=False)
            if result.returncode != 0:
                # Create ftp user
                self._run_command([
                    "useradd", "-r", "-d", "/var/ftp", "-s", "/sbin/nologin", "ftp"
                ], check=False)
                logger.info("Created ftp user")
        except Exception as e:
            logger.warning(f"Could not create ftp user: {e}")
    
    def get_config(self) -> Dict[str, Any]:
        """Get current vsftpd configuration"""
        config = {}
        
        content = self._read_config()
        if not content:
            return config
        
        for line in content.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # Convert value to appropriate type
                if value.upper() == 'YES':
                    config[key] = True
                elif value.upper() == 'NO':
                    config[key] = False
                elif value.isdigit():
                    config[key] = int(value)
                else:
                    config[key] = value
        
        return config
    
    def create_user(
        self,
        username: str,
        password: str,
        home_dir: str = None,
        quota: int = None
    ) -> ServiceResult:
        """Create a virtual FTP user using PAM"""
        try:
            # For vsftpd, we can use system users or virtual users
            # Here we create system users for simplicity
            
            # Check if user exists
            result = self._run_command(["id", username], check=False)
            if result.returncode == 0:
                return ServiceResult(
                    success=False,
                    message=f"User {username} already exists"
                )
            
            # Create home directory
            if home_dir:
                os.makedirs(home_dir, exist_ok=True)
            else:
                home_dir = f"/home/{username}"
                os.makedirs(home_dir, exist_ok=True)
            
            # Create user
            create_cmd = [
                "useradd",
                "-d", home_dir,
                "-s", "/bin/bash",
                "-g", "ftp",
                username
            ]
            self._run_command(create_cmd)
            
            # Set password
            self._run_command(["chpasswd"], input_text=f"{username}:{password}")
            
            # Set ownership
            self._run_command(["chown", "-R", f"{username}:ftp", home_dir])
            
            logger.info(f"Created FTP user: {username}")
            
            return ServiceResult(
                success=True,
                message=f"Created FTP user: {username}",
                data={"username": username, "home_dir": home_dir}
            )
            
        except Exception as e:
            logger.error(f"Failed to create FTP user: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to create FTP user: {username}",
                error=str(e)
            )
    
    def delete_user(self, username: str, remove_home: bool = False) -> ServiceResult:
        """Delete an FTP user"""
        try:
            # Check if user exists
            result = self._run_command(["id", username], check=False)
            if result.returncode != 0:
                return ServiceResult(
                    success=False,
                    message=f"User {username} does not exist"
                )
            
            # Delete user
            cmd = ["userdel"]
            if remove_home:
                cmd.append("-r")
            cmd.append(username)
            
            self._run_command(cmd)
            
            logger.info(f"Deleted FTP user: {username}")
            
            return ServiceResult(
                success=True,
                message=f"Deleted FTP user: {username}"
            )
            
        except Exception as e:
            logger.error(f"Failed to delete FTP user: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to delete FTP user: {username}",
                error=str(e)
            )
    
    def list_users(self) -> list:
        """List FTP users"""
        users = []
        
        try:
            # Get users with ftp group
            result = self._run_command(["getent", "group", "ftp"])
            if result.returncode == 0:
                group_info = result.stdout.strip()
                if ":" in group_info:
                    parts = group_info.split(":")
                    if len(parts) >= 4:
                        users = [u.strip() for u in parts[3].split(",") if u.strip()]
        
        except Exception as e:
            logger.error(f"Failed to list FTP users: {e}")
        
        return users
    
    def get_connections(self) -> list:
        """Get current FTP connections"""
        connections = []
        
        try:
            # Parse vsftpd log or use netstat
            result = self._run_command([
                "ss", "-tn", f"sport = :{self.port}"
            ])
            
            for line in result.stdout.split('\n')[1:]:
                if line.strip():
                    parts = line.split()
                    if len(parts) >= 5:
                        connections.append({
                            "local_addr": parts[3],
                            "remote_addr": parts[4],
                            "state": parts[0] if parts else "unknown"
                        })
        
        except Exception as e:
            logger.error(f"Failed to get FTP connections: {e}")
        
        return connections
    
    def get_info(self) -> Dict[str, Any]:
        """Get comprehensive FTP service information"""
        info = super().get_info()
        
        # Add FTP-specific info
        info.update({
            "ftps_enabled": self.get_config().get("ssl_enable", False),
            "anonymous_enabled": self.get_config().get("anonymous_enable", False),
            "chroot_enabled": self.get_config().get("chroot_local_user", False),
            "passive_ports": f"{self.get_config().get('pasv_min_port', 40000)}-{self.get_config().get('pasv_max_port', 40100)}",
            "users": self.list_users() if self.is_installed() else [],
            "connections": self.get_connections() if self.get_status() == ServiceStatus.RUNNING else []
        })
        
        return info