"""
NFS Service (Network File System)
"""

import os
import re
from typing import Dict, Any, Optional, List
import logging

from .base import BaseService, ServiceResult, ServiceStatus


logger = logging.getLogger(__name__)


class NFSService(BaseService):
    """
    NFS Service implementation for Unix/Linux file sharing.
    """
    
    @property
    def name(self) -> str:
        return "nfs"
    
    @property
    def display_name(self) -> str:
        return "NFS Server"
    
    @property
    def package_name(self) -> str:
        return "nfs-kernel-server" if self.os_type == "debian" else "nfs-utils"
    
    @property
    def service_name(self) -> str:
        return "nfs-kernel-server" if self.os_type == "debian" else "nfs-server"
    
    @property
    def config_path(self) -> str:
        return "/etc/exports"
    
    @property
    def port(self) -> int:
        return 2049
    
    @property
    def default_settings(self) -> Dict[str, Any]:
        return {
            # Default export options
            "default_options": "rw,sync,no_subtree_check,no_root_squash",
            "secure": True,
            "async": False,
            "no_subtree_check": True,
            "root_squash": False,
            
            # NFS versions
            "nfs_versions": ["4.2", "4.1", "4"],
            
            # Port settings (for firewall)
            "mountd_port": 20048,
            "statd_port": 20049,
            "lockd_port": 20050,
            
            # Performance
            "rsize": 1048576,
            "wsize": 1048576,
        }
    
    def configure(self, settings: Dict[str, Any]) -> ServiceResult:
        """Configure NFS server"""
        try:
            # Merge with default settings
            config_settings = {**self.default_settings, **settings}
            
            # Configure NFS ports
            self._configure_nfs_ports(config_settings)
            
            # Create exports file if doesn't exist
            if not os.path.exists(self.config_path):
                self._write_config("# NFS Exports - generated by File Server Manager\n")
            
            # Enable NFS in firewall
            self._setup_firewall()
            
            # Restart service if running
            if self.get_status() == ServiceStatus.RUNNING:
                self.restart()
            
            return ServiceResult(
                success=True,
                message="NFS service configured successfully",
                data={"config_path": self.config_path}
            )
            
        except Exception as e:
            logger.error(f"Failed to configure NFS: {e}")
            return ServiceResult(
                success=False,
                message="Failed to configure NFS service",
                error=str(e)
            )
    
    def _configure_nfs_ports(self, settings: Dict[str, Any]) -> None:
        """Configure static NFS ports"""
        if self.os_type == "debian":
            # Configure /etc/default/nfs-common
            nfs_common = f"""# NFS Common Configuration
STATDOPTS="-p {settings['statd_port']}"
NEED_IDMAPD="yes"
"""
            self._write_config(nfs_common, "/etc/default/nfs-common")
            
            # Configure /etc/default/nfs-kernel-server
            nfs_server = f"""# NFS Server Configuration
RPCNFSDOPTS="-p 2049"
RPCMOUNTDOPTS="-p {settings['mountd_port']}"
"""
            self._write_config(nfs_server, "/etc/default/nfs-kernel-server")
        
        elif self.os_type == "rhel":
            # Configure /etc/sysconfig/nfs
            nfs_sysconfig = f"""# NFS Server Configuration
MOUNTD_PORT={settings['mountd_port']}
STATD_PORT={settings['statd_port']}
LOCKD_PORT={settings['lockd_port']}
"""
            self._write_config(nfs_sysconfig, "/etc/sysconfig/nfs")
    
    def _setup_firewall(self) -> None:
        """Setup firewall rules for NFS"""
        try:
            # Check for firewall type
            if self._command_exists("ufw"):
                self._run_command(["ufw", "allow", "nfs"], check=False)
                self._run_command(["ufw", "allow", "2049/tcp"], check=False)
                self._run_command(["ufw", "allow", "111/tcp"], check=False)
                self._run_command(["ufw", "allow", "111/udp"], check=False)
            elif self._command_exists("firewall-cmd"):
                self._run_command(["firewall-cmd", "--permanent", "--add-service=nfs"], check=False)
                self._run_command(["firewall-cmd", "--permanent", "--add-service=rpc-bind"], check=False)
                self._run_command(["firewall-cmd", "--permanent", "--add-service=mountd"], check=False)
                self._run_command(["firewall-cmd", "--reload"], check=False)
        except Exception as e:
            logger.warning(f"Could not configure firewall: {e}")
    
    def _command_exists(self, command: str) -> bool:
        """Check if command exists"""
        try:
            self._run_command(["which", command], check=False)
            return True
        except Exception:
            return False
    
    def get_config(self) -> Dict[str, Any]:
        """Get current NFS exports"""
        exports = []
        
        content = self._read_config()
        if not content:
            return {"exports": exports}
        
        for line in content.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            # Parse export line: /path host1(options) host2(options)
            parts = line.split()
            if len(parts) >= 2:
                path = parts[0]
                hosts = []
                
                for part in parts[1:]:
                    # Parse host(options)
                    match = re.match(r'([^\(]+)(?:\(([^)]+)\))?', part)
                    if match:
                        host = match.group(1)
                        options = match.group(2) or ""
                        hosts.append({
                            "host": host,
                            "options": options.split(',') if options else []
                        })
                
                exports.append({
                    "path": path,
                    "hosts": hosts
                })
        
        return {"exports": exports}
    
    def create_export(
        self,
        path: str,
        hosts: List[str] = None,
        options: str = None,
        create_dir: bool = True
    ) -> ServiceResult:
        """Create an NFS export"""
        try:
            # Validate path
            if not path or not path.startswith('/'):
                return ServiceResult(
                    success=False,
                    message="Invalid export path"
                )
            
            # Create directory if needed
            if create_dir and not os.path.exists(path):
                os.makedirs(path)
                os.chmod(path, 0o755)
            
            # Default hosts and options
            if not hosts:
                hosts = ["*"]
            
            if not options:
                options = self.default_settings["default_options"]
            
            # Read existing exports
            content = self._read_config() or ""
            
            # Check if export already exists
            for line in content.split('\n'):
                if line.strip().startswith(path + ' ') or line.strip().startswith(path + '\t'):
                    return ServiceResult(
                        success=False,
                        message=f"Export for '{path}' already exists"
                    )
            
            # Build export line
            hosts_str = ' '.join([f"{host}({options})" for host in hosts])
            export_line = f"{path} {hosts_str}\n"
            
            # Append export
            content += export_line
            self._write_config(content)
            
            # Re-export
            self._run_command(["exportfs", "-ra"])
            
            logger.info(f"Created NFS export: {path}")
            
            return ServiceResult(
                success=True,
                message=f"Created NFS export: {path}",
                data={"path": path, "hosts": hosts, "options": options}
            )
            
        except Exception as e:
            logger.error(f"Failed to create NFS export: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to create NFS export: {path}",
                error=str(e)
            )
    
    def delete_export(self, path: str) -> ServiceResult:
        """Delete an NFS export"""
        try:
            content = self._read_config()
            if not content:
                return ServiceResult(
                    success=False,
                    message="No exports configured"
                )
            
            # Find and remove export
            lines = content.split('\n')
            new_lines = []
            found = False
            
            for line in lines:
                if line.strip().startswith(path + ' ') or line.strip().startswith(path + '\t'):
                    found = True
                    continue
                new_lines.append(line)
            
            if not found:
                return ServiceResult(
                    success=False,
                    message=f"Export for '{path}' not found"
                )
            
            # Write updated config
            self._write_config("\n".join(new_lines))
            
            # Unexport and re-export
            self._run_command(["exportfs", "-u", f"{path}"], check=False)
            self._run_command(["exportfs", "-ra"])
            
            logger.info(f"Deleted NFS export: {path}")
            
            return ServiceResult(
                success=True,
                message=f"Deleted NFS export: {path}"
            )
            
        except Exception as e:
            logger.error(f"Failed to delete NFS export: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to delete NFS export: {path}",
                error=str(e)
            )
    
    def list_exports(self) -> List[Dict[str, Any]]:
        """List all NFS exports"""
        config = self.get_config()
        return config.get("exports", [])
    
    def get_active_exports(self) -> List[Dict[str, Any]]:
        """Get currently active exports"""
        exports = []
        
        try:
            result = self._run_command(["exportfs", "-v"], check=False)
            if result.returncode == 0:
                current_path = None
                
                for line in result.stdout.split('\n'):
                    line = line.strip()
                    if not line:
                        continue
                    
                    # New export path
                    if not line.startswith('\t') and ' ' in line:
                        parts = line.split(None, 1)
                        current_path = parts[0]
                        host_info = parts[1] if len(parts) > 1 else ""
                        
                        # Parse host and options
                        match = re.match(r'([^\(]+)(?:\(([^)]+)\))?', host_info)
                        if match:
                            exports.append({
                                "path": current_path,
                                "host": match.group(1),
                                "options": match.group(2).split(',') if match.group(2) else []
                            })
                    elif line.startswith('\t') and current_path:
                        # Additional host for current path
                        host_info = line.strip()
                        match = re.match(r'([^\(]+)(?:\(([^)]+)\))?', host_info)
                        if match:
                            exports.append({
                                "path": current_path,
                                "host": match.group(1),
                                "options": match.group(2).split(',') if match.group(2) else []
                            })
        
        except Exception as e:
            logger.error(f"Failed to get active exports: {e}")
        
        return exports
    
    def get_connections(self) -> List[Dict[str, Any]]:
        """Get current NFS connections"""
        connections = []
        
        try:
            # Use nfsstat or ss to get connections
            result = self._run_command(["ss", "-tn", f"sport = :{self.port}"])
            
            for line in result.stdout.split('\n')[1:]:
                if line.strip():
                    parts = line.split()
                    if len(parts) >= 5:
                        connections.append({
                            "local_addr": parts[3],
                            "remote_addr": parts[4],
                            "state": parts[0] if parts else "unknown"
                        })
        
        except Exception as e:
            logger.error(f"Failed to get NFS connections: {e}")
        
        return connections
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get NFS statistics"""
        stats = {
            "server": {},
            "client": {}
        }
        
        try:
            result = self._run_command(["nfsstat", "-s"], check=False)
            if result.returncode == 0:
                stats["server"]["raw"] = result.stdout
            
            result = self._run_command(["nfsstat", "-c"], check=False)
            if result.returncode == 0:
                stats["client"]["raw"] = result.stdout
        
        except Exception as e:
            logger.error(f"Failed to get NFS statistics: {e}")
        
        return stats
    
    def get_info(self) -> Dict[str, Any]:
        """Get comprehensive NFS service information"""
        info = super().get_info()
        
        info.update({
            "exports": self.list_exports() if self.is_installed() else [],
            "active_exports": self.get_active_exports() if self.get_status() == ServiceStatus.RUNNING else [],
            "connections": self.get_connections() if self.get_status() == ServiceStatus.RUNNING else [],
            "statistics": self.get_statistics() if self.is_installed() else {}
        })
        
        return info