"""
SFTP Service (OpenSSH)
"""

import os
import re
from typing import Dict, Any, Optional, List
import logging

from .base import BaseService, ServiceResult, ServiceStatus


logger = logging.getLogger(__name__)


class SFTPService(BaseService):
    """
    SFTP Service implementation using OpenSSH.
    Provides secure file transfer over SSH.
    """
    
    @property
    def name(self) -> str:
        return "sftp"
    
    @property
    def display_name(self) -> str:
        return "SFTP Server (OpenSSH)"
    
    @property
    def package_name(self) -> str:
        return "openssh-server"
    
    @property
    def service_name(self) -> str:
        return "sshd"
    
    @property
    def config_path(self) -> str:
        return "/etc/ssh/sshd_config"
    
    @property
    def port(self) -> int:
        return 22
    
    @property
    def default_settings(self) -> Dict[str, Any]:
        return {
            # Basic settings
            "port": 22,
            "address_family": "any",
            "listen_address": "0.0.0.0",
            
            # Authentication
            "permit_root_login": "no",
            "password_authentication": "yes",
            "pubkey_authentication": "yes",
            "kbd_interactive_authentication": "no",
            "challenge_response_authentication": "no",
            "use_pam": "yes",
            
            # SFTP specific
            "subsystem_sftp": "/usr/lib/openssh/sftp-server",
            "sftp_chroot": True,
            "sftp_chroot_dir": "/home/%u",
            
            # Security
            "x11_forwarding": "no",
            "allow_agent_forwarding": "no",
            "allow_tcp_forwarding": "no",
            "permit_tunnel": "no",
            "permit_user_environment": "no",
            
            # Limits
            "max_auth_tries": 3,
            "max_sessions": 10,
            "max_startups": "10:30:100",
            
            # Timeouts
            "login_grace_time": 60,
            "client_alive_interval": 300,
            "client_alive_count_max": 2,
            
            # Logging
            "syslog_facility": "AUTH",
            "log_level": "INFO",
            
            # Ciphers and algorithms
            "kex_algorithms": "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256",
            "ciphers": "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com",
            "macs": "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com",
        }
    
    def configure(self, settings: Dict[str, Any]) -> ServiceResult:
        """Configure SSH server for SFTP"""
        try:
            # Merge with default settings
            config_settings = {**self.default_settings, **settings}
            
            # Build configuration content
            config_lines = [
                "# SSH Server configuration - generated by File Server Manager",
                f"# Generated at: {self._get_timestamp()}",
                ""
            ]
            
            # Port and listening
            config_lines.append(f"Port {config_settings.get('port', 22)}")
            
            if config_settings.get("address_family") == "inet":
                config_lines.append("AddressFamily inet")
            elif config_settings.get("address_family") == "inet6":
                config_lines.append("AddressFamily inet6")
            
            listen_addr = config_settings.get("listen_address", "0.0.0.0")
            if listen_addr:
                config_lines.append(f"ListenAddress {listen_addr}")
            
            # Host keys
            config_lines.append("\n# Host Keys")
            for key_file in ["/etc/ssh/ssh_host_rsa_key", "/etc/ssh/ssh_host_ecdsa_key", "/etc/ssh/ssh_host_ed25519_key"]:
                if os.path.exists(key_file):
                    config_lines.append(f"HostKey {key_file}")
            
            # Authentication
            config_lines.append("\n# Authentication")
            config_lines.append(f"PermitRootLogin {config_settings.get('permit_root_login', 'no')}")
            config_lines.append(f"PasswordAuthentication {config_settings.get('password_authentication', 'yes')}")
            config_lines.append(f"PubkeyAuthentication {config_settings.get('pubkey_authentication', 'yes')}")
            config_lines.append(f"KbdInteractiveAuthentication {config_settings.get('kbd_interactive_authentication', 'no')}")
            config_lines.append(f"ChallengeResponseAuthentication {config_settings.get('challenge_response_authentication', 'no')}")
            config_lines.append(f"UsePAM {config_settings.get('use_pam', 'yes')}")
            config_lines.append(f"MaxAuthTries {config_settings.get('max_auth_tries', 3)}")
            
            # SFTP Configuration
            config_lines.append("\n# SFTP Configuration")
            sftp_server = config_settings.get("subsystem_sftp", "/usr/lib/openssh/sftp-server")
            config_lines.append(f"Subsystem sftp {sftp_server}")
            
            # Chroot configuration for SFTP-only users
            if config_settings.get("sftp_chroot"):
                config_lines.append("")
                config_lines.append("# SFTP Chroot Configuration")
                config_lines.append("Match Group sftpusers")
                config_lines.append("    ChrootDirectory %h")
                config_lines.append("    ForceCommand internal-sftp")
                config_lines.append("    AllowTcpForwarding no")
                config_lines.append("    X11Forwarding no")
                config_lines.append("    PermitTunnel no")
            
            # Security settings
            config_lines.append("\n# Security")
            config_lines.append(f"X11Forwarding {config_settings.get('x11_forwarding', 'no')}")
            config_lines.append(f"AllowAgentForwarding {config_settings.get('allow_agent_forwarding', 'no')}")
            config_lines.append(f"AllowTcpForwarding {config_settings.get('allow_tcp_forwarding', 'no')}")
            config_lines.append(f"PermitTunnel {config_settings.get('permit_tunnel', 'no')}")
            config_lines.append(f"PermitUserEnvironment {config_settings.get('permit_user_environment', 'no')}")
            
            # Timeouts
            config_lines.append("\n# Timeouts")
            config_lines.append(f"LoginGraceTime {config_settings.get('login_grace_time', 60)}")
            config_lines.append(f"ClientAliveInterval {config_settings.get('client_alive_interval', 300)}")
            config_lines.append(f"ClientAliveCountMax {config_settings.get('client_alive_count_max', 2)}")
            
            # Logging
            config_lines.append("\n# Logging")
            config_lines.append(f"SyslogFacility {config_settings.get('syslog_facility', 'AUTH')}")
            config_lines.append(f"LogLevel {config_settings.get('log_level', 'INFO')}")
            
            # Limits
            config_lines.append("\n# Limits")
            config_lines.append(f"MaxSessions {config_settings.get('max_sessions', 10)}")
            config_lines.append(f"MaxStartups {config_settings.get('max_startups', '10:30:100')}")
            
            # Cryptographic settings
            if config_settings.get("kex_algorithms"):
                config_lines.append(f"\nKexAlgorithms {config_settings['kex_algorithms']}")
            if config_settings.get("ciphers"):
                config_lines.append(f"Ciphers {config_settings['ciphers']}")
            if config_settings.get("macs"):
                config_lines.append(f"MACs {config_settings['macs']}")
            
            # Write configuration
            config_content = "\n".join(config_lines)
            self._write_config(config_content)
            
            # Create sftpusers group for chroot
            self._ensure_sftp_group()
            
            # Restart service if running
            if self.get_status() == ServiceStatus.RUNNING:
                self.restart()
            
            return ServiceResult(
                success=True,
                message="SFTP service configured successfully",
                data={"config_path": self.config_path}
            )
            
        except Exception as e:
            logger.error(f"Failed to configure SFTP: {e}")
            return ServiceResult(
                success=False,
                message="Failed to configure SFTP service",
                error=str(e)
            )
    
    def _get_timestamp(self) -> str:
        from datetime import datetime
        return datetime.utcnow().isoformat()
    
    def _ensure_sftp_group(self) -> None:
        """Ensure sftpusers group exists for chroot"""
        try:
            result = self._run_command(["getent", "group", "sftpusers"], check=False)
            if result.returncode != 0:
                self._run_command(["groupadd", "sftpusers"])
                logger.info("Created sftpusers group")
        except Exception as e:
            logger.warning(f"Could not create sftpusers group: {e}")
    
    def get_config(self) -> Dict[str, Any]:
        """Get current SSH configuration"""
        config = {}
        
        content = self._read_config()
        if not content:
            return config
        
        for line in content.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            # Handle key-value pairs
            if ' ' in line:
                parts = line.split(None, 1)
                if len(parts) == 2:
                    key = parts[0].lower().replace('-', '_')
                    value = parts[1]
                    config[key] = value
        
        return config
    
    def create_sftp_user(
        self,
        username: str,
        password: str,
        home_dir: str = None,
        chroot: bool = True,
        shell: str = "/sbin/nologin"
    ) -> ServiceResult:
        """Create an SFTP-only user"""
        try:
            # Check if user exists
            result = self._run_command(["id", username], check=False)
            if result.returncode == 0:
                return ServiceResult(
                    success=False,
                    message=f"User {username} already exists"
                )
            
            # Set home directory
            if not home_dir:
                home_dir = f"/home/{username}"
            
            # Create user
            create_cmd = [
                "useradd",
                "-d", home_dir,
                "-s", shell,
                "-G", "sftpusers",
                "-m",
                username
            ]
            self._run_command(create_cmd)
            
            # Set password
            self._run_command(["chpasswd"], input_text=f"{username}:{password}")
            
            # Setup chroot directory
            if chroot:
                self._setup_chroot(username, home_dir)
            
            logger.info(f"Created SFTP user: {username}")
            
            return ServiceResult(
                success=True,
                message=f"Created SFTP user: {username}",
                data={
                    "username": username,
                    "home_dir": home_dir,
                    "chroot_enabled": chroot
                }
            )
            
        except Exception as e:
            logger.error(f"Failed to create SFTP user: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to create SFTP user: {username}",
                error=str(e)
            )
    
    def _setup_chroot(self, username: str, home_dir: str) -> None:
        """Setup chroot directory for SFTP user"""
        # Chroot directory must be owned by root and not writable by others
        # We create a structure: /home/username (root owned) -> /home/username/data (user owned)
        
        try:
            # Ensure parent exists
            os.makedirs(home_dir, exist_ok=True)
            
            # Set chroot directory permissions (root owned, not writable)
            self._run_command(["chown", "root:root", home_dir])
            self._run_command(["chmod", "755", home_dir])
            
            # Create data directory for user files
            data_dir = os.path.join(home_dir, "data")
            os.makedirs(data_dir, exist_ok=True)
            self._run_command(["chown", f"{username}:sftpusers", data_dir])
            self._run_command(["chmod", "750", data_dir])
            
            # Create other standard directories
            for subdir in ["upload", "download"]:
                subdir_path = os.path.join(data_dir, subdir)
                os.makedirs(subdir_path, exist_ok=True)
                self._run_command(["chown", f"{username}:sftpusers", subdir_path])
                self._run_command(["chmod", "750", subdir_path])
            
            logger.info(f"Setup chroot for {username}")
            
        except Exception as e:
            logger.warning(f"Could not setup chroot: {e}")
    
    def delete_user(self, username: str, remove_home: bool = False) -> ServiceResult:
        """Delete an SFTP user"""
        try:
            # Check if user exists
            result = self._run_command(["id", username], check=False)
            if result.returncode != 0:
                return ServiceResult(
                    success=False,
                    message=f"User {username} does not exist"
                )
            
            # Delete user
            cmd = ["userdel"]
            if remove_home:
                cmd.append("-r")
            cmd.append(username)
            
            self._run_command(cmd)
            
            logger.info(f"Deleted SFTP user: {username}")
            
            return ServiceResult(
                success=True,
                message=f"Deleted SFTP user: {username}"
            )
            
        except Exception as e:
            logger.error(f"Failed to delete SFTP user: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to delete SFTP user: {username}",
                error=str(e)
            )
    
    def list_users(self) -> List[Dict[str, Any]]:
        """List SFTP users"""
        users = []
        
        try:
            # Get users in sftpusers group
            result = self._run_command(["getent", "group", "sftpusers"])
            if result.returncode == 0:
                group_info = result.stdout.strip()
                if ":" in group_info:
                    parts = group_info.split(":")
                    if len(parts) >= 4:
                        usernames = [u.strip() for u in parts[3].split(",") if u.strip()]
                        
                        for uname in usernames:
                            # Get user info
                            user_result = self._run_command(["getent", "passwd", uname], check=False)
                            if user_result.returncode == 0:
                                user_parts = user_result.stdout.strip().split(":")
                                users.append({
                                    "username": uname,
                                    "uid": int(user_parts[2]) if len(user_parts) > 2 else None,
                                    "gid": int(user_parts[3]) if len(user_parts) > 3 else None,
                                    "home_dir": user_parts[5] if len(user_parts) > 5 else None,
                                    "shell": user_parts[6] if len(user_parts) > 6 else None
                                })
        
        except Exception as e:
            logger.error(f"Failed to list SFTP users: {e}")
        
        return users
    
    def get_connections(self) -> List[Dict[str, Any]]:
        """Get current SFTP connections"""
        connections = []
        
        try:
            result = self._run_command(["ss", "-tn", f"sport = :{self.port}"])
            
            for line in result.stdout.split('\n')[1:]:
                if line.strip():
                    parts = line.split()
                    if len(parts) >= 5:
                        connections.append({
                            "local_addr": parts[3],
                            "remote_addr": parts[4],
                            "state": parts[0] if parts else "unknown"
                        })
        
        except Exception as e:
            logger.error(f"Failed to get SFTP connections: {e}")
        
        return connections
    
    def add_authorized_key(self, username: str, public_key: str) -> ServiceResult:
        """Add SSH public key for user"""
        try:
            # Get user home directory
            result = self._run_command(["getent", "passwd", username])
            if result.returncode != 0:
                return ServiceResult(
                    success=False,
                    message=f"User {username} not found"
                )
            
            home_dir = result.stdout.strip().split(":")[5]
            ssh_dir = os.path.join(home_dir, ".ssh")
            auth_keys_file = os.path.join(ssh_dir, "authorized_keys")
            
            # Create .ssh directory
            os.makedirs(ssh_dir, mode=0o700, exist_ok=True)
            
            # Add key to authorized_keys
            with open(auth_keys_file, 'a') as f:
                f.write(public_key.strip() + "\n")
            
            # Set permissions
            self._run_command(["chown", "-R", f"{username}:{username}", ssh_dir])
            os.chmod(auth_keys_file, 0o600)
            
            logger.info(f"Added authorized key for {username}")
            
            return ServiceResult(
                success=True,
                message=f"Added authorized key for {username}"
            )
            
        except Exception as e:
            logger.error(f"Failed to add authorized key: {e}")
            return ServiceResult(
                success=False,
                message=f"Failed to add authorized key",
                error=str(e)
            )
    
    def get_info(self) -> Dict[str, Any]:
        """Get comprehensive SFTP service information"""
        info = super().get_info()
        
        config = self.get_config()
        
        info.update({
            "pubkey_auth_enabled": config.get("pubkey_authentication", "yes") == "yes",
            "password_auth_enabled": config.get("password_authentication", "yes") == "yes",
            "root_login_disabled": config.get("permit_root_login", "no") in ["no", "prohibit-password"],
            "chroot_enabled": "Match Group sftpusers" in (self._read_config() or ""),
            "users": self.list_users() if self.is_installed() else [],
            "connections": self.get_connections() if self.get_status() == ServiceStatus.RUNNING else []
        })
        
        return info